/**
 * Copyright (C) 2018 - 2026 bolthur project.
 *
 * This file is part of bolthur/kernel.
 *
 * bolthur/kernel is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * bolthur/kernel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with bolthur/kernel.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _CONSTANTS_H
#define _CONSTANTS_H

// usb
#define PERIPHERAL_USB_OFFSET 0x980000
#define PERIPHERAL_USB_CORE_OFFSET PERIPHERAL_USB_OFFSET
#define PERIPHERAL_USB_HOST_OFFSET PERIPHERAL_USB_OFFSET + 0x400
#define PERIPHERAL_USB_POWER_OFFSET PERIPHERAL_USB_OFFSET + 0xE00
// dwhci core
#define PERIPHERAL_DWHCI_CORE_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x000
#define PERIPHERAL_DWHCI_CORE_OTG_INIT PERIPHERAL_USB_CORE_OFFSET + 0x004
#define PERIPHERAL_DWHCI_CORE_AHB_CFG PERIPHERAL_USB_CORE_OFFSET + 0x008
#define PERIPHERAL_DWHCI_CORE_USB_CFG PERIPHERAL_USB_CORE_OFFSET + 0x00C
#define PERIPHERAL_DWHCI_CORE_RESET PERIPHERAL_USB_CORE_OFFSET + 0x010
#define PERIPHERAL_DWHCI_CORE_INT_STAT PERIPHERAL_USB_CORE_OFFSET + 0x014
#define PERIPHERAL_DWHCI_CORE_INT_MASK PERIPHERAL_USB_CORE_OFFSET + 0x018
#define PERIPHERAL_DWHCI_CORE_RX_STAT_RD PERIPHERAL_USB_CORE_OFFSET + 0x01C
#define PERIPHERAL_DWHCI_CORE_RX_STAT_POP PERIPHERAL_USB_CORE_OFFSET + 0x020
#define PERIPHERAL_DWHCI_CORE_RX_FIFO_SIZ PERIPHERAL_USB_CORE_OFFSET + 0x024
#define PERIPHERAL_DWHCI_CORE_NPER_FIFO_SIZ PERIPHERAL_USB_CORE_OFFSET + 0x028
#define PERIPHERAL_DWHCI_CORE_NPER_TX_STAT PERIPHERAL_USB_CORE_OFFSET + 0x02C
#define PERIPHERAL_DWHCI_CORE_I2C_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x030
#define PERIPHERAL_DWHCI_CORE_PHY_VENDOR_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x034
#define PERIPHERAL_DWHCI_CORE_GPIO PERIPHERAL_USB_CORE_OFFSET + 0x038
#define PERIPHERAL_DWHCI_CORE_USER_ID PERIPHERAL_USB_CORE_OFFSET + 0x03C
#define PERIPHERAL_DWHCI_CORE_VENDOR_ID PERIPHERAL_USB_CORE_OFFSET + 0x040
#define PERIPHERAL_DWHCI_CORE_HW_CFG1 PERIPHERAL_USB_CORE_OFFSET + 0x044
#define PERIPHERAL_DWHCI_CORE_HW_CFG2 PERIPHERAL_USB_CORE_OFFSET + 0x048
#define PERIPHERAL_DWHCI_CORE_HW_CFG3 PERIPHERAL_USB_CORE_OFFSET + 0x04C
#define PERIPHERAL_DWHCI_CORE_HW_CFG4 PERIPHERAL_USB_CORE_OFFSET + 0x050
#define PERIPHERAL_DWHCI_CORE_LPM_CFG PERIPHERAL_USB_CORE_OFFSET + 0x054
#define PERIPHERAL_DWHCI_CORE_POWER_DOWN PERIPHERAL_USB_CORE_OFFSET + 0x058
#define PERIPHERAL_DWHCI_CORE_DFIFO_CFG PERIPHERAL_USB_CORE_OFFSET + 0x05C
#define PERIPHERAL_DWHCI_CORE_ADP_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x060
#define PERIPHERAL_DWHCI_CORE_MDIO_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x080
#define PERIPHERAL_DWHCI_CORE_MDIO_DATA PERIPHERAL_USB_CORE_OFFSET + 0x084
#define PERIPHERAL_DWHCI_CORE_VBUS_DRV_CTRL PERIPHERAL_USB_CORE_OFFSET + 0x088
#define PERIPHERAL_DWHCI_CORE_HOST_PER_TX_FIFO_SZ PERIPHERAL_USB_CORE_OFFSET + 0x100
#define PERIPHERAL_DWHCI_CORE_DEV_PER_TX_FIFO( fifo ) ( PERIPHERAL_USB_CORE_OFFSET + 0x104 + ( fifo ) * 4 )
#define PERIPHERAL_DWHCI_CORE_DEV_TX_FIFO( fifo ) ( PERIPHERAL_USB_CORE_OFFSET + 0x108 + ( fifo ) * 4 )
// dwhci host
#define PERIPHERAL_DWHCI_HOST_CFG PERIPHERAL_USB_HOST_OFFSET + 0x000
#define PERIPHERAL_DWHCI_HOST_FRM_INTERVAL PERIPHERAL_USB_HOST_OFFSET + 0x004
#define PERIPHERAL_DWHCI_HOST_FRM_NUM PERIPHERAL_USB_HOST_OFFSET + 0x008
#define PERIPHERAL_DWHCI_HOST_PER_TX_FIFO_STAT PERIPHERAL_USB_HOST_OFFSET + 0x010
#define PERIPHERAL_DWHCI_HOST_ALLCHAN_INT PERIPHERAL_USB_HOST_OFFSET + 0x014
#define PERIPHERAL_DWHCI_HOST_ALLCHAN_INT_MASK PERIPHERAL_USB_HOST_OFFSET + 0x018
#define PERIPHERAL_DWHCI_HOST_FRMLST_BASE PERIPHERAL_USB_HOST_OFFSET + 0x01C
#define PERIPHERAL_DWHCI_HOST_PORT PERIPHERAL_USB_HOST_OFFSET + 0x040
#define PERIPHERAL_DWHCI_HOST_CHAN_CHARACTER( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x100 + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_CHAN_SPLIT_CTRL( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x104 + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_CHAN_INT( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x108 + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_CHAN_INT_MASK( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x10C + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_CHAN_XFER_SIZE( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x110 + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_HOST_CHAN_DMA_ADDR( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x114 + ( chan ) * 0x20 )
#define PERIPHERAL_DWHCI_HOST_HOST_CHAN_DMA_BUF( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x11C + ( chan ) * 0x20 )
// dwhci data fifo ( non dma only )
#define PERIPHERAL_DWHCI_DATA_FIFO_SIZE 0x1000
#define PERIPHERAL_DWHCI_MAX_CHANNELS	16
#define PERIPHERAL_DWHCI_DATA_FIFO( chan ) ( PERIPHERAL_USB_HOST_OFFSET + 0x1000 + ( chan ) * PERIPHERAL_DWHCI_DATA_FIFO_SIZE )

#endif //_CONSTANTS_H
