/**
* Copyright (C) 2018 - 2026 bolthur project.
 *
 * This file is part of bolthur/kernel.
 *
 * bolthur/kernel is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * bolthur/kernel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with bolthur/kernel.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _PLATFORM_RASPI_LIBHCD_H
#define _PLATFORM_RASPI_LIBHCD_H

// interrupt
#define ARM_IRQ_USB 9

// core interrupts
#define HCD_CORE_INTERRUPT_CURRENT_MODE ( 1U << 0 )
#define HCD_CORE_INTERRUPT_MODE_MISMATCH ( 1U << 1 )
#define HCD_CORE_INTERRUPT_OTG ( 1U << 2 )
#define HCD_CORE_INTERRUPT_DMA_START_OF_FRAME ( 1U << 3 )
#define HCD_CORE_INTERRUPT_RECEIVE_STATUS_LEVEL ( 1U << 4 )
#define HCD_CORE_INTERRUPT_NP_TRANSMIT_FIFO_EMPTY ( 1U << 5 )
#define HCD_CORE_INTERRUPT_GINNAKEFF ( 1U << 6 )
#define HCD_CORE_INTERRUPT_GOUTNAKEFF ( 1U << 7 )
#define HCD_CORE_INTERRUPT_ULPICK ( 1U << 8 )
#define HCD_CORE_INTERRUPT_I2C ( 1U << 9 )
#define HCD_CORE_INTERRUPT_EARLY_SUSPEND ( 1U << 10 )
#define HCD_CORE_INTERRUPT_USB_SUSPEND ( 1U << 11 )
#define HCD_CORE_INTERRUPT_USB_RESET ( 1U << 12 )
#define HCD_CORE_INTERRUPT_ENUMARTION_DONE ( 1U << 13 )
#define HCD_CORE_INTERRUPT_ISOCHRONOUS_OUT_DROP ( 1U << 14 )
#define HCD_CORE_INTERRUPT_EOPFRAME ( 1U << 15 )
#define HCD_CORE_INTERRUPT_RESTORE_DONE ( 1U << 16 )
#define HCD_CORE_INTERRUPT_END_POINT_MISMATCH ( 1U << 17 )
#define HCD_CORE_INTERRUPT_IN_END_POINT ( 1U << 18 )
#define HCD_CORE_INTERRUPT_OUT_END_POINT ( 1U << 19 )
#define HCD_CORE_INTERRUPT_INCOMPLETE_ISOCHRONOUS_IN ( 1U << 20 )
#define HCD_CORE_INTERRUPT_INCOMPLETE_ISOCHRONOUS_OUT ( 1U << 21 )
#define HCD_CORE_INTERRUPT_FETSETUP ( 1U << 22 )
#define HCD_CORE_INTERRUPT_RESET_DETECT ( 1U << 23 )
#define HCD_CORE_INTERRUPT_PORT ( 1U << 24 )
#define HCD_CORE_INTERRUPT_HOST_CHANNEL ( 1U << 25 )
#define HCD_CORE_INTERRUPT_HP_TRANSMIT_FIFO_EMPTY ( 1U << 26 )
#define HCD_CORE_INTERRUPT_LOW_POWER_MODE_TRANSMIT_RECEIVED ( 1U << 27 )
#define HCD_CORE_INTERRUPT_CONNECTION_ID_STATUS_CHANGE ( 1U << 28 )
#define HCD_CORE_INTERRUPT_DISCONNECT ( 1U << 29 )
#define HCD_CORE_INTERRUPT_SESSION_REQUEST ( 1U << 30 )
#define HCD_CORE_INTERRUPT_WAKEUP ( 1U << 31 )

// channel interrupts
#define HCD_CHANNEL_INTERRUPT_TRANSFER_COMPLETE ( 1U << 0 )
#define HCD_CHANNEL_INTERRUPT_HALT ( 1U << 1 )
#define HCD_CHANNEL_INTERRUPT_AHB_ERROR ( 1U << 2 )
#define HCD_CHANNEL_INTERRUPT_STALL ( 1U << 3 )
#define HCD_CHANNEL_INTERRUPT_NEGATIVE_ACKNOWLEDGEMENT ( 1U << 4 )
#define HCD_CHANNEL_INTERRUPT_ACKNOWLEDGEMENT ( 1U << 5 )
#define HCD_CHANNEL_INTERRUPT_NOT_YET ( 1U << 6 )
#define HCD_CHANNEL_INTERRUPT_TRANSACTION_ERROR ( 1U << 7 )
#define HCD_CHANNEL_INTERRUPT_BABBLE_ERROR ( 1U << 8 )
#define HCD_CHANNEL_INTERRUPT_FRAME_OVERRUN ( 1U << 9 )
#define HCD_CHANNEL_INTERRUPT_DATA_TOGGLE_ERROR ( 1U << 10 )
#define HCD_CHANNEL_INTERRUPT_BUFFER_NOT_AVAILABLE ( 1U << 11 )
#define HCD_CHANNEL_INTERRUPT_EXCESSIVE_TRANSMISSION ( 1U << 12 )
#define HCD_CHANNEL_INTERRUPT_FRAME_LIST_ROLLOVER ( 1U << 13 )
#define HCD_CHANNEL_INTERRUPT_RESERVED 0xffffc000
#define HCD_CHANNEL_INTERRUPT_ERROR_MASK ( \
  HCD_CHANNEL_INTERRUPT_AHB_ERROR \
  | HCD_CHANNEL_INTERRUPT_STALL \
  | HCD_CHANNEL_INTERRUPT_TRANSACTION_ERROR \
  | HCD_CHANNEL_INTERRUPT_BABBLE_ERROR \
  | HCD_CHANNEL_INTERRUPT_FRAME_OVERRUN \
  | HCD_CHANNEL_INTERRUPT_DATA_TOGGLE_ERROR)

// fifo stuff
#define HCD_DWHCI_CFG_HOST_RX_FIFO_SIZE 516 // number of 32 bit words
#define HCD_DWHCI_CFG_HOST_NPER_TX_FIFO_SIZE 256 // number of 32 bit words
#define HCD_DWHCI_CFG_HOST_PER_TX_FIFO_SIZE 252 // number of 32 bit words

// dwhci core ahb config values
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_INTERRUPT_MASK ( 1U << 0 )
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_MAX_AXI_BURST_SHIFT ( 1U << 0 ) // bcm2835 only
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_MAX_AXI_BURST_MASK ( 3U << 1 ) // bcm2835 only
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_WAIT_AXI_WRITES ( 1U << 4 ) // bcm2835 only
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_DMA_ENABLE ( 1U << 5 )
#define HCD_DWHCI_CORE_AHB_CFG_GLOBAL_AHB_SINGLE ( 1U << 23 )
// dwhci core usb config values
 #define HCD_DWHCI_CORE_USB_CFG_PHYIF ( 1U << 3 )
 #define HCD_DWHCI_CORE_USB_CFG_ULPI_UTMI_SEL ( 1U << 4 )
 #define HCD_DWHCI_CORE_USB_CFG_SRP_CAPABLE ( 1U << 8 )
 #define HCD_DWHCI_CORE_USB_CFG_HNP_CAPABLE ( 1U << 9 )
 #define HCD_DWHCI_CORE_USB_CFG_ULPI_FSLS ( 1U << 17 )
 #define HCD_DWHCI_CORE_USB_CFG_ULPI_CLK_SUS_M ( 1U << 19 )
 #define HCD_DWHCI_CORE_USB_CFG_ULPI_EXT_VBUS_DRV ( 1U << 20 )
 #define HCD_DWHCI_CORE_USB_CFG_TERM_SEL_DL_PULSE ( 1U << 22 )
// dwhci reset usb values
 #define HCD_DWHCI_CORE_RESET_SOFT_RESET ( 1U << 0 )
 #define HCD_DWHCI_CORE_RESET_RX_FIFO_FLUSH ( 1U << 4 )
 #define HCD_DWHCI_CORE_RESET_TX_FIFO_FLUSH ( 1U << 5 )
 #define HCD_DWHCI_CORE_RESET_TX_FIFO_NUM_SHIFT 6
 #define HCD_DWHCI_CORE_RESET_TX_FIFO_NUM_MASK ( 0x1F << 6 )
 #define HCD_DWHCI_CORE_RESET_AHB_IDLE ( 1U << 31 )
// dwhci cfg2 values
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE( reg ) ( ( ( reg ) >> 0 ) & 7 )
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_HNP_SRP_CAPABLE 0
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_SRP_ONLY_CAPABLE 1
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_NO_HNP_SRP_CAPABLE 2
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_SRP_CAPABLE_DEVICE 3
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_NO_SRP_CAPABLE_DEVICE 4
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_SRP_CAPABLE_HOST 5
#define HCD_DWHCI_CORE_HW_CFG2_OP_MODE_NO_SRP_CAPABLE_HOST 6
#define HCD_DWHCI_CORE_HW_CFG2_ARCHITECTURE( reg ) ( ( ( reg ) >> 3 ) & 3 )
#define HCD_DWHCI_CORE_HW_CFG2_ARCHITECTURE_SLAVE_ONLY 0
#define HCD_DWHCI_CORE_HW_CFG2_ARCHITECTURE_EXTERNAL_DMA 1
#define HCD_DWHCI_CORE_HW_CFG2_ARCHITECTURE_INTERNAL_DMA 2
#define HCD_DWHCI_CORE_HW_CFG2_HS_PHY_TYPE( reg ) ( ( ( reg ) >> 6 ) & 3 )
#define HCD_DWHCI_CORE_HW_CFG2_HS_PHY_TYPE_NOT_SUPPORTED 0
#define HCD_DWHCI_CORE_HW_CFG2_HS_PHY_TYPE_UTMI 1
#define HCD_DWHCI_CORE_HW_CFG2_HS_PHY_TYPE_ULPI 2
#define HCD_DWHCI_CORE_HW_CFG2_HS_PHY_TYPE_UTMI_ULPI 3
#define HCD_DWHCI_CORE_HW_CFG2_FS_PHY_TYPE( reg ) ( ( ( reg ) >> 8 ) & 3 )
#define HCD_DWHCI_CORE_HW_CFG2_FS_PHY_TYPE_PHYSICAL0 0
#define HCD_DWHCI_CORE_HW_CFG2_FS_PHY_TYPE_DEDICATED 1
#define HCD_DWHCI_CORE_HW_CFG2_FS_PHY_TYPE_PHYSICAL1 2
#define HCD_DWHCI_CORE_HW_CFG2_FS_PHY_TYPE_PHYSICAL2 3
#define HCD_DWHCI_CORE_HW_CFG2_NUM_HOST_CHANNELS( reg ) ( ( ( ( reg ) >> 14 ) & 0xF ) + 1 )
// dwhci host cfg values
#define HCD_DWHCI_HOST_CFG_FSLS_PCLK_SEL_SHIFT 0
#define HCD_DWHCI_HOST_CFG_FSLS_PCLK_SEL_MASK ( 3U << 0 )
#define HCD_DWHCI_HOST_CFG_FSLS_PCLK_SEL_30_60_MHZ 0
#define HCD_DWHCI_HOST_CFG_FSLS_PCLK_SEL_48_MHZ 1
#define HCD_DWHCI_HOST_CFG_FSLS_PCLK_SEL_6_MHZ 2
#define HCD_DWHCI_HOST_CFG_FSLS_ONLY ( 1U << 2 )
#define HCD_DWHCI_HOST_CFG_ENABLE_DMA_DESCRIPTOR ( 1U << 23 )
// dwhci host port values
#define HCD_DWHCI_HOST_PORT_CONNECT ( 1U << 0 )
#define HCD_DWHCI_HOST_PORT_CONNECT_CHANGED ( 1U << 1 )
#define HCD_DWHCI_HOST_PORT_ENABLE ( 1U << 2 )
#define HCD_DWHCI_HOST_PORT_ENABLE_CHANGED ( 1U << 3 )
#define HCD_DWHCI_HOST_PORT_OVERCURRENT ( 1U << 4 )
#define HCD_DWHCI_HOST_PORT_OVERCURRENT_CHANGED ( 1U << 5 )
#define HCD_DWHCI_HOST_PORT_RESUME ( 1U << 6 )
#define HCD_DWHCI_HOST_PORT_SUSPEND ( 1U << 7 )
#define HCD_DWHCI_HOST_PORT_RESET ( 1U << 8 )
#define HCD_DWHCI_HOST_PORT_POWER ( 1U << 12 )
#define HCD_DWHCI_HOST_PORT_SPEED( reg ) ( ( ( reg ) >> 17 ) & 0x3 )
#define HCD_DWHCI_HOST_PORT_TEST_CONTROL( reg ) ( ( ( reg ) >> 13 ) & 0xf )
#define HCD_DWHCI_HOST_PORT_SPEED_HIGH 0
#define HCD_DWHCI_HOST_PORT_SPEED_FULL 1
#define HCD_DWHCI_HOST_PORT_SPEED_LOW 2
#define HCD_DWHCI_HOST_PORT_DEFAULT_MASK ( HCD_DWHCI_HOST_PORT_CONNECT_CHANGED \
 | HCD_DWHCI_HOST_PORT_ENABLE | HCD_DWHCI_HOST_PORT_ENABLE_CHANGED \
 | HCD_DWHCI_HOST_PORT_OVERCURRENT_CHANGED )
// core interrupt values
#define HCD_DWHCI_CORE_INT_MASK_HOST_MODE ( 1U << 0 )
#define HCD_DWHCI_CORE_INT_MASK_MODE_MISMATCH ( 1U << 1 )
#define HCD_DHWCI_CORE_INT_MASK_OTG_INTR ( 1U << 2 )
#define HCD_DWHCI_CORE_INT_MASK_SOF_INTR ( 1U << 3 )
#define HCD_DWHCI_CORE_INT_MASK_RX_STS_Q_LVL ( 1U << 4 )
#define HCD_DWHCI_CORE_INT_MASK_NP_TX_FE_EMPTY ( 1U << 5 )
#define HCD_DWHCI_CORE_INT_MASK_USB_SUSPEND ( 1U << 11 )
#define HCD_DWHCI_CORE_INT_MASK_PORT_INTR ( 1U << 24 )
#define HCD_DWHCI_CORE_INT_MASK_HC_INTR ( 1U << 25 )
#define HCD_DWHCI_CORE_INT_MASK_CON_ID_STS_CHNG ( 1U << 28 )
#define HCD_DWHCI_CORE_INT_MASK_DISCONNECT ( 1U << 29 )
#define HCD_DWHCI_CORE_INT_MASK_SESS_REQ_INTR ( 1U << 30 )
#define HCD_DWHCI_CORE_INT_MASK_WKUP_INTR ( 1U << 31 )
// power reg
#define HCD_DWHCI_POWER_REGISTER_STOP_P_CLOCK ( 1U << 0 )
#define HCD_DWHCI_POWER_REGISTER_GATE_H_CLOCK ( 1U << 1 )
#define HCD_DWHCI_POWER_REGISTER_POWER_CLAMP ( 1U << 2 )
#define HCD_DWHCI_POWER_REGISTER_POWER_DOWN_MODULES ( 1U << 3 )
#define HCD_DWHCI_POWER_REGISTER_PHY_SUSPENDED ( 1U << 4 )
#define HCD_DWHCI_POWER_REGISTER_ENABLE_SLEEP_CLOCK_GATING ( 1U << 5 )
#define HCD_DWHCI_POWER_REGISTER_PHY_SLEEPING ( 1U << 6 )
#define HCD_DWHCI_POWER_REGISTER_DEEP_SLEEP ( 1U << 7 )

// characteristics
#define HCD_DWHCI_CHAN_CHARACTER_MAXIMUM_PACKET_SIZE( val ) ( ( ( uint32_t )val ) & 0x7ff )
#define HCD_DWHCI_CHAN_CHARACTER_END_POINT_NUMBER( val ) ( ( ( ( uint32_t )val ) & 0xf ) << 11 )
#define HCD_DWHCI_CHAN_CHARACTER_END_POINT_DIRECTION( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 15 )
#define HCD_DWHCI_CHAN_CHARACTER_LOW_SPEED( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 17 )
#define HCD_DWHCI_CHAN_CHARACTER_TYPE( val ) ( ( ( ( uint32_t )val ) & 0x3 ) << 18 )
#define HCD_DWHCI_CHAN_CHARACTER_PACKETS_PER_FRAME( val ) ( ( ( ( uint32_t )val ) & 0x3 ) << 20 )
#define HCD_DWHCI_CHAN_CHARACTER_DEVICE_ADDRESS( val ) ( ( ( ( uint32_t )val ) & 0x7f ) << 22 )
#define HCD_DWHCI_CHAN_CHARACTER_INTERVAL( val ) ( ( ( ( uint32_t )val ) & 0x3f ) << 26 )
#define HCD_DWHCI_CHAN_CHARACTER_ODD_FRAME( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 29 )
#define HCD_DWHCI_CHAN_CHARACTER_DISABLE( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 30 )
#define HCD_DWHCI_CHAN_CHARACTER_ENABLE( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 31 )
#define HCD_DWHCI_CHAN_CHARACTER_MAXIMUM_PACKET_SIZE_MASK 0x7ff
// split control
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_PORT_ADDRESS( val ) ( ( ( uint32_t )val ) & 0x7f )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_HUB_ADDRESS( val ) ( ( ( ( uint32_t )val ) & 0x7f ) << 7 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_TRANSACTION_POSITION( val ) ( ( ( ( uint32_t )val ) & 0x3 ) << 14 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_COMPLETE_SPLIT( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 16 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_SPLIT_ENABLE( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 31 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_EXTRACT_PORT_ADDRESS( val ) ( ( ( uint32_t )val ) & 0x7f )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_EXTRACT_HUB_ADDRESS( val ) ( ( ( ( uint32_t )val ) & 0x7f ) << 7 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_EXTRACT_TRANSACTION_POSITION( val ) ( ( ( ( uint32_t )val ) & 0x3 ) << 14 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_EXTRACT_COMPLETE_SPLIT( val ) ( ( ( ( uint32_t )val ) & 0x1 ) << 16 )
#define HCD_DWHCI_CHAN_SPLIT_CONTROL_EXTRACT_SPLIT_ENABLE ( 1U << 31 )
// xfer
#define HCD_DWHCI_CHAN_XFER_SIZE_TRANSFER_SIZE_MASK 0x7ffffU
#define HCD_DWHCI_CHAN_XFER_SIZE_PACKET_COUNT_MASK 0x3ffU << 19
#define HCD_DWHCI_CHAN_XFER_SIZE_TRANSFER_SIZE( val ) ( ( val ) & 0x7ffff )
#define HCD_DWHCI_CHAN_XFER_SIZE_PACKET_COUNT( val ) ( ( ( val ) & 0x3ff ) << 19 )
#define HCD_DWHCI_CHAN_XFER_SIZE_PACKET_ID( val ) ( ( ( val ) & 0x3 ) << 29 )

// core ctrl stuff
#define HCD_DWHCI_CORE_CTRL_HOST_SET_NP_ENABLE ( 1U << 10 )

#endif
