/**
 * Copyright (C) 2018 - 2022 bolthur project.
 *
 * This file is part of bolthur/kernel.
 *
 * bolthur/kernel is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * bolthur/kernel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with bolthur/kernel.  If not, see <http://www.gnu.org/licenses/>.
 */

#if ! defined( _LIBPERIPHERAL_H )
#define _LIBPERIPHERAL_H

// initial setup of peripheral base
#if defined( BCM2836 ) || defined( BCM2837 )
  #define PERIPHERAL_BASE 0x3F000000
  #define PERIPHERAL_SIZE 0xFFFFFF
#else
  #define PERIPHERAL_BASE 0x20000000
  #define PERIPHERAL_SIZE 0xFFFFFF
#endif

// mailbox offset
#define PERIPHERAL_MAILBOX_OFFSET 0xB880
// random number generator
#define PERIPHERAL_RNG_OFFSET 0x104000
#define PERIPHERAL_RNG_CONTROL PERIPHERAL_RNG_OFFSET + 0x00
#define PERIPHERAL_RNG_STATUS PERIPHERAL_RNG_OFFSET + 0x04
#define PERIPHERAL_RNG_DATA PERIPHERAL_RNG_OFFSET + 0x08
#define PERIPHERAL_RNG_INTERRUPT PERIPHERAL_RNG_OFFSET + 0x10
// gpio
#define PERIPHERAL_GPIO_OFFSET 0x200000
#define PERIPHERAL_GPIO_GPFSEL0 PERIPHERAL_GPIO_OFFSET
#define PERIPHERAL_GPIO_GPFSEL1 PERIPHERAL_GPIO_OFFSET + 0x04
#define PERIPHERAL_GPIO_GPFSEL2 PERIPHERAL_GPIO_OFFSET + 0x08
#define PERIPHERAL_GPIO_GPFSEL3 PERIPHERAL_GPIO_OFFSET + 0x0C
#define PERIPHERAL_GPIO_GPFSEL4 PERIPHERAL_GPIO_OFFSET + 0x10
#define PERIPHERAL_GPIO_GPFSEL5 PERIPHERAL_GPIO_OFFSET + 0x14
#define PERIPHERAL_GPIO_GPSET0 PERIPHERAL_GPIO_OFFSET + 0x1C
#define PERIPHERAL_GPIO_GPSET1 PERIPHERAL_GPIO_OFFSET + 0x20
#define PERIPHERAL_GPIO_GPCLR0 PERIPHERAL_GPIO_OFFSET + 0x28
#define PERIPHERAL_GPIO_GPCLR1 PERIPHERAL_GPIO_OFFSET + 0x2C
#define PERIPHERAL_GPIO_GPLEV0 PERIPHERAL_GPIO_OFFSET + 0x34
#define PERIPHERAL_GPIO_GPLEV1 PERIPHERAL_GPIO_OFFSET + 0x38
#define PERIPHERAL_GPIO_GPEDS0 PERIPHERAL_GPIO_OFFSET + 0x40
#define PERIPHERAL_GPIO_GPEDS1 PERIPHERAL_GPIO_OFFSET + 0x44
#define PERIPHERAL_GPIO_GPREN0 PERIPHERAL_GPIO_OFFSET + 0x4C
#define PERIPHERAL_GPIO_GPREN1 PERIPHERAL_GPIO_OFFSET + 0x50
#define PERIPHERAL_GPIO_GPFEN0 PERIPHERAL_GPIO_OFFSET + 0x58
#define PERIPHERAL_GPIO_GPFEN1 PERIPHERAL_GPIO_OFFSET + 0x5C
#define PERIPHERAL_GPIO_GPHEN0 PERIPHERAL_GPIO_OFFSET + 0x64
#define PERIPHERAL_GPIO_GPHEN1 PERIPHERAL_GPIO_OFFSET + 0x68
#define PERIPHERAL_GPIO_GPLEN0 PERIPHERAL_GPIO_OFFSET + 0x70
#define PERIPHERAL_GPIO_GPLEN1 PERIPHERAL_GPIO_OFFSET + 0x74
#define PERIPHERAL_GPIO_GPAREN0 PERIPHERAL_GPIO_OFFSET + 0x7C
#define PERIPHERAL_GPIO_GPAREN1 PERIPHERAL_GPIO_OFFSET + 0x80
#define PERIPHERAL_GPIO_GPAFEN0 PERIPHERAL_GPIO_OFFSET + 0x88
#define PERIPHERAL_GPIO_GPAFEN1 PERIPHERAL_GPIO_OFFSET + 0x8C
#define PERIPHERAL_GPIO_GPPUD PERIPHERAL_GPIO_OFFSET + 0x94
#define PERIPHERAL_GPIO_GPPUDCLK0 PERIPHERAL_GPIO_OFFSET + 0x98
#define PERIPHERAL_GPIO_GPPUDCLK1 PERIPHERAL_GPIO_OFFSET + 0x9C
// emmc
#define PERIPHERAL_EMMC_OFFSET 0x300000
#define PERIPHERAL_EMMC_ARG2 PERIPHERAL_EMMC_OFFSET
#define PERIPHERAL_EMMC_BLKSIZECNT PERIPHERAL_EMMC_OFFSET + 0x04
#define PERIPHERAL_EMMC_ARG1 PERIPHERAL_EMMC_OFFSET + 0x08
#define PERIPHERAL_EMMC_CMDTM PERIPHERAL_EMMC_OFFSET + 0x0C
#define PERIPHERAL_EMMC_RESP0 PERIPHERAL_EMMC_OFFSET + 0x10
#define PERIPHERAL_EMMC_RESP1 PERIPHERAL_EMMC_OFFSET + 0x14
#define PERIPHERAL_EMMC_RESP2 PERIPHERAL_EMMC_OFFSET + 0x18
#define PERIPHERAL_EMMC_RESP3 PERIPHERAL_EMMC_OFFSET + 0x1C
#define PERIPHERAL_EMMC_DATA PERIPHERAL_EMMC_OFFSET + 0x20
#define PERIPHERAL_EMMC_STATUS PERIPHERAL_EMMC_OFFSET + 0x24
#define PERIPHERAL_EMMC_CONTROL0 PERIPHERAL_EMMC_OFFSET + 0x28
#define PERIPHERAL_EMMC_CONTROL1 PERIPHERAL_EMMC_OFFSET + 0x2C
#define PERIPHERAL_EMMC_INTERRUPT PERIPHERAL_EMMC_OFFSET + 0x30
#define PERIPHERAL_EMMC_IRPT_MASK PERIPHERAL_EMMC_OFFSET + 0x34
#define PERIPHERAL_EMMC_IRPT_ENABLE PERIPHERAL_EMMC_OFFSET + 0x38
#define PERIPHERAL_EMMC_CONTROL2 PERIPHERAL_EMMC_OFFSET + 0x3C
#define PERIPHERAL_EMMC_CAPABILITY1 PERIPHERAL_EMMC_OFFSET + 0x40
#define PERIPHERAL_EMMC_CAPABILITY2 PERIPHERAL_EMMC_OFFSET + 0x44
#define PERIPHERAL_EMMC_FORCE_IRPT PERIPHERAL_EMMC_OFFSET + 0x50
#define PERIPHERAL_EMMC_BOOT_TIMEOUT PERIPHERAL_EMMC_OFFSET + 0x70
#define PERIPHERAL_EMMC_DBG_SEL PERIPHERAL_EMMC_OFFSET + 0x74
#define PERIPHERAL_EMMC_EXRDFIFO_CFG PERIPHERAL_EMMC_OFFSET + 0x80
#define PERIPHERAL_EMMC_EXRDFIFO_EN PERIPHERAL_EMMC_OFFSET + 0x84
#define PERIPHERAL_EMMC_TUNE_STEP PERIPHERAL_EMMC_OFFSET + 0x88
#define PERIPHERAL_EMMC_TUNE_STEPS_STD PERIPHERAL_EMMC_OFFSET + 0x8C
#define PERIPHERAL_EMMC_TUNE_STEPS_DDR PERIPHERAL_EMMC_OFFSET + 0x90
#define PERIPHERAL_EMMC_SPI_INT_SPT PERIPHERAL_EMMC_OFFSET + 0xF0
#define PERIPHERAL_EMMC_SLOTISR_VER PERIPHERAL_EMMC_OFFSET + 0xFC
// usb
#define PERIPHERAL_USB_OFFSET 0x980000

#endif
