/**
 * Copyright (C) 2018 - 2023 bolthur project.
 *
 * This file is part of bolthur/kernel.
 *
 * bolthur/kernel is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * bolthur/kernel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with bolthur/kernel.  If not, see <http://www.gnu.org/licenses/>.
 */

#if ! defined( _LIBSDHOST_H )
#define _LIBSDHOST_H

// command register
#define SDHOST_COMMAND_FLAG_ENABLE ( 1 << 15 )
#define SDHOST_COMMAND_FLAG_FAILED ( 1 << 14 )
#define SDHOST_COMMAND_FLAG_BUSY ( 1 << 11 )
#define SDHOST_COMMAND_FLAG_RESPONSE_NONE ( 1 << 10 )
#define SDHOST_COMMAND_FLAG_RESPONSE_LONG ( 1 << 9 )
#define SDHOST_COMMAND_FLAG_WRITE ( 1 << 7 )
#define SDHOST_COMMAND_FLAG_READ ( 1 << 6 )
#define SDHOST_COMMAND_FLAG_COMMAND_MASK 0x3F
// host status
#define SDHOST_HOST_STATUS_HAVEDATA ( 1 << 0 )
#define SDHOST_HOST_STATUS_ERROR_FIFO ( 1 << 3 )
#define SDHOST_HOST_STATUS_ERROR_CRC7 ( 1 << 4 )
#define SDHOST_HOST_STATUS_ERROR_CRC16 ( 1 << 5 )
#define SDHOST_HOST_STATUS_TIMEOUT_CMD ( 1 << 6 )
#define SDHOST_HOST_STATUS_TIMEOUT_DATA ( 1 << 7 )
#define SDHOST_HOST_STATUS_INT_SDIO ( 1 << 8 )
#define SDHOST_HOST_STATUS_INT_BLOCK ( 1 << 9 )
#define SDHOST_HOST_STATUS_INT_BUSY ( 1 << 10 )

#define SDHOST_HOST_STATUS_RESET 0xFFFF

#define SDHOST_HOST_STATUS_MASK_ERROR_DATA ( \
  SDHOST_HOST_STATUS_ERROR_FIFO \
  | SDHOST_HOST_STATUS_ERROR_CRC7 \
  | SDHOST_HOST_STATUS_ERROR_CRC16 \
  | SDHOST_HOST_STATUS_TIMEOUT_DATA )

#define SDHOST_HOST_STATUS_MASK_ERROR_ALL ( \
  SDHOST_HOST_STATUS_MASK_ERROR_DATA \
  | SDHOST_HOST_STATUS_TIMEOUT_CMD )


// host config
#define SDHOST_HOST_CONFIG_INTBUS_WIDE ( 1 << 1 )
#define SDHOST_HOST_CONFIG_EXTBUS_4BIT ( 1 << 2 )
#define SDHOST_HOST_CONFIG_SLOW_CARD ( 1 << 3 )
#define SDHOST_HOST_CONFIG_INTERRUPT_ENABLE_DATA ( 1 << 4 )
#define SDHOST_HOST_CONFIG_INTERRUPT_ENABLE_SDIO ( 1 << 5 )
#define SDHOST_HOST_CONFIG_INTERRUPT_ENABLE_BLOCK ( 1 << 8 )
#define SDHOST_HOST_CONFIG_INTERRUPT_ENABLE_BUSY ( 1 << 10 )
// clock divisor
#define SDHOST_CLOCKDIVISOR_MAXVAL 0x07FF
// debug register
#define SDHOST_DEBUG_FORCE_DATA_MODE ( 1 << 19 )
#define SDHOST_DEBUG_CLOCK_PULSE ( 1 << 20 )
#define SDHOST_DEBUG_BYPASS ( 1 << 21 )

#define SDHOST_DEBUG_THRESHOLD_WRITE_SHIFT 9
#define SDHOST_DEBUG_THRESHOLD_READ_SHIFT 14
#define SDHOST_DEBUG_THRESHOLD_MASK 0x1F

#define SDHOST_DEBUG_FSM_MASK 0xF
#define SDHOST_DEBUG_FSM_IDENTMODE 0x0
#define SDHOST_DEBUG_FSM_DATAMODE 0x1
#define SDHOST_DEBUG_FSM_READDATA 0x2
#define SDHOST_DEBUG_FSM_WRITEDATA 0x3
#define SDHOST_DEBUG_FSM_READWAIT 0x4
#define SDHOST_DEBUG_FSM_READCRC 0x5
#define SDHOST_DEBUG_FSM_WRITECRC 0x6
#define SDHOST_DEBUG_FSM_WRITEWAIT1 0x7
#define SDHOST_DEBUG_FSM_POWERDOWN 0x8
#define SDHOST_DEBUG_FSM_POWERUP 0x9
#define SDHOST_DEBUG_FSM_WRITESTART1 0xA
#define SDHOST_DEBUG_FSM_WRITESTART2 0xB
#define SDHOST_DEBUG_FSM_GENPULSES 0xC
#define SDHOST_DEBUG_FSM_WRITEWAIT2 0xD
#define SDHOST_DEBUG_FSM_STARTPOWDOWN 0xF
// settings
#define SDHOST_FIFO_SIZE 16
#define SDHOST_FIFO_THRESHOLD_READ 4
#define SDHOST_FIFO_THRESHOLD_WRITE 4
#define SDHOST_DATA_FIFO_PIO_BURST 8

#define SDHOST_TIMEOUT_DEFAULT 0xF00000

#define SDHOST_DATA_FIFO_WORD 16

#define SDHOST_DEBUG_FIFO_FILL_SHIFT 4
#define SDHOST_DEBUG_FIFO_FILL_MASK  0x1F
#define SDHOST_DEBUG_FIFO_FILL( reg ) ( \
  ( reg >> SDHOST_DEBUG_FIFO_FILL_SHIFT ) & SDHOST_DEBUG_FIFO_FILL_MASK )

// helpers for command stuff
#define SDHOST_CMD_INDEX( a ) ( a & SDHOST_COMMAND_FLAG_COMMAND_MASK )
#define SDHOST_CMD_RESERVED( a ) 0xFFFFFFFF
#define SDHOST_CMD_WHO_KNOWS( a ) SDHOST_CMD_RESERVED( a )
#define SDHOST_CMD_UNUSED( a ) SDHOST_CMD_RESERVED( a )
#define SDHOST_APP_CMD_BIT ( 1u << 31 )
#define SDHOST_APP_CMD_TO_CMD( a ) ( a & SDHOST_COMMAND_FLAG_COMMAND_MASK )
#define SDHOST_CMD_TO_APP_CMD( a ) ( SDHOST_APP_CMD_BIT | a )
#define SDHOST_CMD_IS_RESERVED( a ) ( a == SDHOST_CMD_RESERVED( a ) )
#define SDHOST_APP_CMD_INDEX( a ) ( SDHOST_APP_CMD_BIT | SDHOST_CMD_INDEX( a ) )
#define SDHOST_IS_APP_CMD( a ) ( a & SDHOST_APP_CMD_BIT )

// command response types
#define SDHOST_CMD_RESPONSE_NONE SDHOST_COMMAND_FLAG_RESPONSE_NONE
#define SDHOST_CMD_RESPONSE_R1 0
#define SDHOST_CMD_RESPONSE_R1b SDHOST_COMMAND_FLAG_BUSY
#define SDHOST_CMD_RESPONSE_R2 SDHOST_COMMAND_FLAG_RESPONSE_LONG
#define SDHOST_CMD_RESPONSE_R3 0
#define SDHOST_CMD_RESPONSE_R4 SDHOST_COMMAND_FLAG_RESPONSE_LONG /// FIXME: SHOULD BE 48
#define SDHOST_CMD_RESPONSE_R5 0
#define SDHOST_CMD_RESPONSE_R6 0
#define SDHOST_CMD_RESPONSE_R7 0

// supported command types
#define SDHOST_CMD_GO_IDLE_STATE 0
#define SDHOST_CMD_ALL_SEND_CID 2
#define SDHOST_CMD_SEND_RELATIVE_ADDR 3
#define SDHOST_CMD_SET_DSR 4
#define SDHOST_CMD_IO_SEND_OP_COND 5
#define SDHOST_CMD_SWITCH_FUNC 6
#define SDHOST_CMD_SELECT_CARD 7
#define SDHOST_CMD_DESELECT_CARD SDHOST_CMD_SELECT_CARD
#define SDHOST_CMD_SEND_IF_COND 8
#define SDHOST_CMD_SEND_CSD 9
#define SDHOST_CMD_SEND_CID 10
#define SDHOST_CMD_VOLTAGE_SWITCH 11
#define SDHOST_CMD_STOP_TRANSMISSION 12
#define SDHOST_CMD_SEND_STATUS 13
#define SDHOST_CMD_SEND_TASK_STATUS SDHOST_CMD_SEND_STATUS
#define SDHOST_CMD_GO_INACTIVE_STATE 15
#define SDHOST_CMD_SET_BLOCKLEN 16
#define SDHOST_CMD_READ_SINGLE_BLOCK 17
#define SDHOST_CMD_READ_MULTIPLE_BLOCK 18
#define SDHOST_CMD_SEND_TUNING_BLOCK 19
#define SDHOST_CMD_SPEED_CLASS_CONTROL 20
#define SDHOST_CMD_ADDRESS_EXTENSION 22
#define SDHOST_CMD_SET_BLOCK_COUNT 23
#define SDHOST_CMD_WRITE_SINGLE_BLOCK 24
#define SDHOST_CMD_WRITE_MULTIPLE_BLOCK 25
#define SDHOST_CMD_PROGRAM_CSD 27
#define SDHOST_CMD_SET_WRITE_PROT 28
#define SDHOST_CMD_CLR_WRITE_PROT 29
#define SDHOST_CMD_SEND_WRITE_PROT 30
#define SDHOST_CMD_ERASE_WR_BLK_START 32
#define SDHOST_CMD_ERASE_WR_BLK_END 33
#define SDHOST_CMD_ERASE 38
#define SDHOST_CMD_LOCK_UNLOCK 42
#define SDHOST_CMD_APP_CMD 55
#define SDHOST_CMD_GEN_CMD 56
// app command types
#define SDHOST_APP_CMD_SET_BUS_WIDTH SDHOST_CMD_TO_APP_CMD( 6 )
#define SDHOST_APP_CMD_SD_STATUS SDHOST_CMD_TO_APP_CMD( 13 )
#define SDHOST_APP_CMD_SEND_NUM_WR_BLOCKS SDHOST_CMD_TO_APP_CMD( 22 )
#define SDHOST_APP_CMD_SET_WR_BLK_ERASE_COUNT SDHOST_CMD_TO_APP_CMD( 23 )
#define SDHOST_APP_CMD_SD_SEND_OP_COND SDHOST_CMD_TO_APP_CMD( 41 )
#define SDHOST_APP_CMD_SET_CLR_CARD_DETECT SDHOST_CMD_TO_APP_CMD( 42 )
#define SDHOST_APP_CMD_SEND_SCR SDHOST_CMD_TO_APP_CMD( 51 )

// ocr bit set
#define SDHOST_OCR_MEM_READY ( 1 << 31 ) // memory power-up status bit
#define SDHOST_OCR_HCS ( 1 << 30 ) // SD only
#define SDHOST_OCR_ACCESS_MODE_MASK ( 3 << 29 ) // MMC only
#define SDHOST_OCR_ACCESS_MODE_BYTE ( 0 << 29 ) // MMC only
#define SDHOST_OCR_ACCESS_MODE_SECTOR ( 2 << 29 ) // MMC only
#define SDHOST_OCR_S18A ( 1 << 24 )
#define SDHOST_OCR_3_5V_3_6V ( 1 << 23 )
#define SDHOST_OCR_3_4V_3_5V ( 1 << 22 )
#define SDHOST_OCR_3_3V_3_4V ( 1 << 21 )
#define SDHOST_OCR_3_2V_3_3V ( 1 << 20 )
#define SDHOST_OCR_3_1V_3_2V ( 1 << 19 )
#define SDHOST_OCR_3_0V_3_1V ( 1 << 18 )
#define SDHOST_OCR_2_9V_3_0V ( 1 << 17 )
#define SDHOST_OCR_2_8V_2_9V ( 1 << 16 )
#define SDHOST_OCR_2_7V_2_8V ( 1 << 15 )
#define SDHOST_OCR_2_6V_2_7V ( 1 << 14 )
#define SDHOST_OCR_2_5V_2_6V ( 1 << 13 )
#define SDHOST_OCR_2_4V_2_5V ( 1 << 12 )
#define SDHOST_OCR_2_3V_2_4V ( 1 << 11 )
#define SDHOST_OCR_2_2V_2_3V ( 1 << 10 )
#define SDHOST_OCR_2_1V_2_2V ( 1 << 9 )
#define SDHOST_OCR_2_0V_2_1V ( 1 << 8 )
#define SDHOST_OCR_1_9V_2_0V ( 1 << 7 )
#define SDHOST_OCR_1_8V_1_9V ( 1 << 6 )
#define SDHOST_OCR_1_7V_1_8V ( 1 << 5 )
#define SDHOST_OCR_1_6V_1_7V ( 1 << 4 )

// sd card versions
#define SDHOST_CARD_VERSION_UNKNOWN 0
#define SDHOST_CARD_VERSION_1 1
#define SDHOST_CARD_VERSION_1_1 2
#define SDHOST_CARD_VERSION_2 3
#define SDHOST_CARD_VERSION_3 4
#define SDHOST_CARD_VERSION_4 5
#define SDHOST_CARD_VERSION_5 6
#define SDHOST_CARD_VERSION_6 7
#define SDHOST_CARD_VERSION_7 8
#define SDHOST_CARD_VERSION_8 9

// possible clock frequencies
#define SDHOST_CLOCK_FREQUENCY_LOW 0
#define SDHOST_CLOCK_FREQUENCY_NORMAL 25000000

#endif
